# Generated by Django 2.2.9 on 2020-05-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_companysetup_yearlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=40)),
                ('user_pass', models.CharField(max_length=200)),
                ('user_mobile', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=120, unique=True)),
                ('user_address', models.CharField(max_length=10)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.CompanySetup')),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.CountryList')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.YearList')),
            ],
        ),
    ]
