# Generated by Django 2.2.9 on 2020-05-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0004_productbrand_productcategory_productinfo_purchaseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='purchase_invo',
            field=models.IntegerField(default=0),
        ),
    ]
