# Generated by Django 2.2.9 on 2020-05-22 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0005_purchaseinfo_purchase_invo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 14, 25, 148092, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
