# Generated by Django 2.2.9 on 2020-05-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0006_purchaseinfo_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(default=0)),
                ('current_quantity', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.ProductBrand')),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.ProductCategory')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.ProductInfo')),
            ],
        ),
    ]
