# Generated by Django 2.2.9 on 2020-05-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0007_productinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_invo', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('total_vat', models.FloatField(default=0)),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.ProductBrand')),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.ProductCategory')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.ProductInfo')),
                ('sales_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.UserList')),
            ],
        ),
    ]
