# Generated by Django 2.2.9 on 2020-05-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0008_salesinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_month', models.DateTimeField()),
                ('to_month', models.DateTimeField()),
                ('from_amount', models.IntegerField(default=0)),
                ('to_amount', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.CountryList')),
            ],
        ),
    ]
