# Generated by Django 2.2.9 on 2020-05-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0009_discountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinfo',
            name='sales_complete',
            field=models.BooleanField(default=False),
        ),
    ]
