# Generated by Django 2.2.9 on 2020-05-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0010_salesinfo_sales_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('generate_date', models.DateTimeField(auto_now_add=True)),
                ('used_date', models.DateTimeField()),
            ],
        ),
    ]
