# Generated by Django 2.2.9 on 2020-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0011_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
    ]
