# Generated by Django 2.2.9 on 2020-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0012_giftcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
