# Generated by Django 2.2.9 on 2020-05-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0013_auto_20200524_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceWiseDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_invo', models.IntegerField(default=0)),
                ('total_discount', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
